POST https://messages-rest-api.onrender.com/api/write_message/
Content-Type: application/json

{
    "sender": "abra",
    "receiver": "ofek",
    "message": "You passed!",
    "subject": "Home assignment",
    "is_read": false
}

###

GET https://messages-rest-api.onrender.com/api/user/ofek/messages/
Content-Type: application/json

###

POST https://messages-rest-api.onrender.com/api/signup/
Content-Type: application/json

{
    "username": "ofek",
    "password": "ofek",
    "email": "ofekharpaz6@gmail.com"
}

###

#fill in the token returned in the signup
GET https://messages-rest-api.onrender.com/api/user/ofek/messages/
Content-Type: application/json
Authorization: Token 97ff4543987cfa683580e49a3e7f0113373694e7 

###

POST https://messages-rest-api.onrender.com/api/write_message/
Content-Type: application/json

{
    "sender": "abra",
    "receiver": "ofek",
    "message": "This message is already read",
    "subject": "ReadMessage",
    "is_read": true
}

###

#fill in the token returned in the signup
GET https://messages-rest-api.onrender.com/api/user/ofek/unread-messages/
Content-Type: application/json
Authorization: Token 97ff4543987cfa683580e49a3e7f0113373694e7 

###

#fill in the token returned in the signup
GET https://messages-rest-api.onrender.com/api/user/ofek/messages/
Content-Type: application/json
Authorization: Token 97ff4543987cfa683580e49a3e7f0113373694e7

###

GET https://messages-rest-api.onrender.com/api/user/ofek/messages/read/
Content-Type: application/json

###

#fill in the token returned in the signup
GET https://messages-rest-api.onrender.com/api/user/ofek/unread-messages/
Content-Type: application/json
Authorization: Token 97ff4543987cfa683580e49a3e7f0113373694e7

###

DELETE https://messages-rest-api.onrender.com/api/user/ofek/messages/ReadMessage/delete/
Content-Type: application/json

###

#fill in the token returned in the signup
GET https://messages-rest-api.onrender.com/api/user/ofek/messages/
Content-Type: application/json
Authorization: Token 97ff4543987cfa683580e49a3e7f0113373694e7

###

#EDGE CASES:
#Username already taken
POST https://messages-rest-api.onrender.com/api/signup/
Content-Type: application/json

{
    "username": "ofek",
    "password": "ofek"
}

###

#No user exists
POST https://messages-rest-api.onrender.com/api/login/
Content-Type: application/json

{
    "username": "name",
    "password": "password"
}
###

#Invalid credentials
POST https://messages-rest-api.onrender.com/api/login/
Content-Type: application/json

{
    "username": "ofek",
    "password": "password"
}
###

#Invalid token
GET https://messages-rest-api.onrender.com/api/user/ofek/messages/
Content-Type: application/json
Authorization: Token xxx

###

#Message deleted doesnt exist
DELETE https://messages-rest-api.onrender.com/api/user/ofek/messages/NonExistingMessage/delete/
Content-Type: application/json

###

#There is no unread message (run until all are read)
GET https://messages-rest-api.onrender.com/api/user/ofek/messages/read/
Content-Type: application/json






















